export const LOGIN_USERNAME = 'LOGIN_USERNAME';
export const LOGIN_PASSWORD = 'LOGIN_PASSWORD';

export const POST_USERNAME_AND_PASSWORD_SUCCESS = 'POST_USERNAME_SUCCESS';
export const POST_USERNAME_AND_PASSWORD_FAILURE = 'POST_USERNAME_FAILURE';

